### PR TITLE
ci: add integration tests

### LINKED ISSUE #6: [TASK] Setup integration test
**User story**
The current project is out of date and needs integration tests to make sure it is compatible with stable argo api

**Acceptance Criteria**
- [ ] github action that submits a dsl generated workflow

### PR DESCRIPTION
**Pull request by paguos**
Add initial implementation of integration tests.

This approach uses the Argo CLI, it will be possible to do it with the argo-client (wanted to avoid the dependency for integration test).

Closes #6.

### CODE REVIEW

**Comment by binarycrayon** [comment]
@paguos this is great! Let me know if you still have more commits to come or this is ready for review.

**Comment by paguos** [comment]
@binarycrayon can you review the process first? If you're ok with how the tests work I will add the rest of the workflows and some docs ;)

**Comment by yxue-kabam** [comment]
LGTM, let me know how you want to process (I can merge this then you start a new PR or you continue to work on this pr)

**Review by binarycrayon — APPROVED** [review]

**Comment by binarycrayon** [comment]
Let me know how you want to proceed, I can merge this then you start a new pr, or you can continue working on this pr

**Comment by paguos** [comment]
> Let me know how you want to proceed, I can merge this then you start a new pr, or you can continue working on this pr

Can you merge it with the label: `hacktoberfest-accepted`? :) I will open a follow-up PR to include more workflows

**Comment by binarycrayon** [comment]
@paguos Thanks!

**Pull request merged**
