### PR TITLE
feat: Add CronWorkflow DSL

### LINKED ISSUE #3: Support for CronWorkflow
I am really enjoying using this DSL for standard Argo workflows and I was wondering if there any plans to add support for Argo's `CronWorkflow`. I would find that feature very useful.

### PR DESCRIPTION
**Pull request by paguos**
Closes #3.

**Note:** There is a lot of unnecessary duplicated code for both `Workflow` and `CronWorkflow`. The current metaclass implementation makes it difficult to use inheritance without rewritting a majority of the existing code.

### CODE REVIEW

**Comment by binarycrayon** [comment]
LGTM

**Comment by binarycrayon** [comment]
@paguos Let me know if it's ready to be merged

**Comment by binarycrayon** [comment]
I agree that it's not necessary to modify the existing class (CronWorkflow and Workflow are 2 separate models in argo-python-client anyway)

I may not have time to do a release earlier than the weekend, feel free to add adjustment till then.

Thanks for your contribution!

**Comment by paguos** [comment]
> @paguos Let me know if it's ready to be merged

Yes :) I'll try to include WorkflowTemplates and WorkflowClusterTemplates in another PR 😉

**Review by binarycrayon — APPROVED** [review]

**Comment by binarycrayon** [comment]
great to hear, thanks again!

**Pull request merged**
